In [1]:
import numpy as np

In [12]:
data1 = [6,7.5,8,0,1]
arr1= np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
arr1.shape

(5,)

In [15]:
data2= [[1,2,3,4],[5,6,7,8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.shape

(2, 4)

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr = np.array([1,2,3,4,5], dtype = np.int64)

In [26]:
arr.dtype

dtype('int64')

In [29]:
float_arr = arr.astype(np.float64)

In [30]:
float_arr

array([1., 2., 3., 4., 5.])

In [31]:
float_arr.dtype

dtype('float64')

In [37]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype = np.float64)
arr2 = np.array([[7,8,9], [10,11,12]], dtype = np.float64)

In [38]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [6]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9]], dtype = np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [23]:
arr1[0,]

array([1., 2., 3.])

In [24]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [25]:
arr1[1,2]=0
arr1

array([[1., 2., 3.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [32]:
names = np.array(['charles','kilho', 'hayoung','charles','hayoung','kilho','kilho'])
data = np.random.randn(7,4)
names

array(['charles', 'kilho', 'hayoung', 'charles', 'hayoung', 'kilho',
       'kilho'], dtype='<U7')

In [28]:
data

array([[-0.99237675,  0.6450773 ,  1.02183081, -0.93873356],
       [ 1.71555514, -0.80733872, -2.56674506, -0.4572029 ],
       [-2.28051703,  0.45295949,  1.28547594, -1.08627197],
       [ 0.09261502,  1.51315736,  0.47662166,  0.94597665],
       [-0.40400808, -1.0712692 ,  1.76560049, -0.04813086],
       [ 0.52193681, -1.09924691,  0.0827812 ,  0.38023962],
       [-0.02882051, -0.01516179, -0.60166014, -1.03647622]])

In [30]:
dataa = np.random.randn(7,4)

In [33]:
names == 'charles'

array([ True, False, False,  True, False, False, False])

In [36]:
data [ names=='charles', :]

array([[ 1.57978242, -0.62821666,  0.05773599, -0.42725743],
       [ 0.18780487, -0.72745895,  2.53706696,  0.23329117]])

In [37]:
data [ (names=='charles') | (names == 'kilho'), :]

array([[ 1.57978242e+00, -6.28216665e-01,  5.77359852e-02,
        -4.27257435e-01],
       [ 6.46468446e-04, -5.38101830e-01,  4.90296420e-01,
         1.08677806e+00],
       [ 1.87804874e-01, -7.27458952e-01,  2.53706696e+00,
         2.33291175e-01],
       [ 1.75969608e+00, -1.52370429e+00,  2.04565567e-01,
         2.05993467e+00],
       [-2.53999592e-01,  1.61999090e+00,  8.99744596e-01,
         1.24521106e-01]])

In [39]:
data [ (data[:,3] <0) , :]

array([[ 1.57978242, -0.62821666,  0.05773599, -0.42725743]])

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
x = np.random.randn(8)
y = np.random.randn(8)

In [43]:
arr.sum()

45

In [46]:
arr.max()

9

In [48]:
data

array([[ 1.57978242e+00, -6.28216665e-01,  5.77359852e-02,
        -4.27257435e-01],
       [ 6.46468446e-04, -5.38101830e-01,  4.90296420e-01,
         1.08677806e+00],
       [ 8.01502409e-01, -1.37204455e+00, -3.22233644e-01,
         5.34548915e-02],
       [ 1.87804874e-01, -7.27458952e-01,  2.53706696e+00,
         2.33291175e-01],
       [-2.17869725e-01, -1.76495855e+00,  3.73166454e-01,
         1.16304144e+00],
       [ 1.75969608e+00, -1.52370429e+00,  2.04565567e-01,
         2.05993467e+00],
       [-2.53999592e-01,  1.61999090e+00,  8.99744596e-01,
         1.24521106e-01]])

In [49]:
data.sum(axis = 0)

array([ 3.85756293, -4.93449394,  4.24034234,  4.2937639 ])

In [50]:
data.sum(axis = 1)

array([ 0.5820443 ,  1.03961912, -0.83932089,  2.23070406, -0.44662039,
        2.50049203,  2.39025701])

In [53]:
(data >0).sum()

18

In [55]:
arr = np.random.randn(8)
arr

array([ 1.31668571, -2.05373151, -1.40244245, -0.49193687, -0.1187449 ,
        1.18283571,  0.00591182, -1.47934061])

In [60]:
np.sort(arr)[::-1]

array([ 1.31668571,  1.18283571,  0.00591182, -0.1187449 , -0.49193687,
       -1.40244245, -1.47934061, -2.05373151])

In [61]:
np.sort(arr, axis=0)

array([-2.05373151, -1.47934061, -1.40244245, -0.49193687, -0.1187449 ,
        0.00591182,  1.18283571,  1.31668571])

In [63]:
np.sort(data, axis =1)

array([[-6.28216665e-01, -4.27257435e-01,  5.77359852e-02,
         1.57978242e+00],
       [-5.38101830e-01,  6.46468446e-04,  4.90296420e-01,
         1.08677806e+00],
       [-1.37204455e+00, -3.22233644e-01,  5.34548915e-02,
         8.01502409e-01],
       [-7.27458952e-01,  1.87804874e-01,  2.33291175e-01,
         2.53706696e+00],
       [-1.76495855e+00, -2.17869725e-01,  3.73166454e-01,
         1.16304144e+00],
       [-1.52370429e+00,  2.04565567e-01,  1.75969608e+00,
         2.05993467e+00],
       [-2.53999592e-01,  1.24521106e-01,  8.99744596e-01,
         1.61999090e+00]])

In [64]:
np.sort(data)[::-1]

array([[-2.53999592e-01,  1.24521106e-01,  8.99744596e-01,
         1.61999090e+00],
       [-1.52370429e+00,  2.04565567e-01,  1.75969608e+00,
         2.05993467e+00],
       [-1.76495855e+00, -2.17869725e-01,  3.73166454e-01,
         1.16304144e+00],
       [-7.27458952e-01,  1.87804874e-01,  2.33291175e-01,
         2.53706696e+00],
       [-1.37204455e+00, -3.22233644e-01,  5.34548915e-02,
         8.01502409e-01],
       [-5.38101830e-01,  6.46468446e-04,  4.90296420e-01,
         1.08677806e+00],
       [-6.28216665e-01, -4.27257435e-01,  5.77359852e-02,
         1.57978242e+00]])

In [67]:
array_10 = np.random.randn(10)
array_10

array([ 1.84520745,  0.48754922,  0.7738262 , -0.84233439, -0.07449917,
        0.19763201, -2.05383642,  0.15154244,  0.17786864,  1.20484548])

In [68]:
np.sort(array_10)[::-1]

array([ 1.84520745,  1.20484548,  0.7738262 ,  0.48754922,  0.19763201,
        0.17786864,  0.15154244, -0.07449917, -0.84233439, -2.05383642])

In [73]:
np.sort(array_10[ 0:(int(0.1*len(array_10)))]) [::-1]

array([1.84520745])

In [75]:
np.unique(names)

array(['charles', 'hayoung', 'kilho'], dtype='<U7')

In [1]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj.dtype

dtype('int64')

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index= ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.name = '조재성패밀리'
obj2.index.name = '이름'

In [11]:
obj2

이름
d    4
b    7
a   -5
c    3
Name: 조재성패밀리, dtype: int64

In [13]:
df = pd.DataFrame({ 'name ' : ['kilho' , 'kilho', 'kilho', 'charles', 'charles'],
                  'year' : [2014, 2015, 2016, 2015, 2016],
                  'points' : [1.5, 1.7, 3.6, 2.4, 2.9]})

df

name   year  points
0    kilho  2014     1.5
1    kilho  2015     1.7
2    kilho  2016     3.6
3  charles  2015     2.4
4  charles  2016     2.9

In [14]:
df.columns

Index(['name ', 'year', 'points'], dtype='object')

In [15]:
df.values

array([['kilho', 2014, 1.5],
       ['kilho', 2015, 1.7],
       ['kilho', 2016, 3.6],
       ['charles', 2015, 2.4],
       ['charles', 2016, 2.9]], dtype=object)

In [16]:
df.index.name = 'num'
df.columns.name ='info'

In [17]:
df

info    name   year  points
num                        
0       kilho  2014     1.5
1       kilho  2015     1.7
2       kilho  2016     3.6
3     charles  2015     2.4
4     charles  2016     2.9

In [27]:
data ={ 'name ' : ['kilho' , 'kilho', 'kilho', 'charles', 'charles'],
                  'year' : [2014, 2015, 2016, 2015, 2016],
                  'points' : [1.5, 1.7, 3.6, 2.4, 2.9]}

In [23]:
df2 = pd.DataFrame(data, columns=['year', 'points','name','penalty_new'],
                  index=['one','two', 'three','four','five'])

In [24]:
df2

year  points name penalty_new
one    2014     1.5  NaN         NaN
two    2015     1.7  NaN         NaN
three  2016     3.6  NaN         NaN
four   2015     2.4  NaN         NaN
five   2016     2.9  NaN         NaN

In [25]:
df.describe()

info         year    points
count     5.00000  5.000000
mean   2015.20000  2.420000
std       0.83666  0.864292
min    2014.00000  1.500000
25%    2015.00000  1.700000
50%    2015.00000  2.400000
75%    2016.00000  2.900000
max    2016.00000  3.600000

In [30]:
df2

year  points name penalty_new
one    2014     1.5  NaN         NaN
two    2015     1.7  NaN         NaN
three  2016     3.6  NaN         NaN
four   2015     2.4  NaN         NaN
five   2016     2.9  NaN         NaN

In [31]:
df = pd.DataFrame( data, columns=['year','names','points','penalty'],
                 index= ['one','two','threes','four','five'])

In [32]:
df

year names  points penalty
one     2014   NaN     1.5     NaN
two     2015   NaN     1.7     NaN
threes  2016   NaN     3.6     NaN
four    2015   NaN     2.4     NaN
five    2016   NaN     2.9     NaN

In [33]:
df[['year']]

year
one     2014
two     2015
threes  2016
four    2015
five    2016

In [36]:
df['zeros'] = np.arange(5)

In [37]:
df

year names  points penalty  zeros
one     2014   NaN     1.5     NaN      0
two     2015   NaN     1.7     NaN      1
threes  2016   NaN     3.6     NaN      2
four    2015   NaN     2.4     NaN      3
five    2016   NaN     2.9     NaN      4

In [1]:
import numpy as np
import pandas as pd

In [23]:
data ={ 'names ' : ['kilho' , 'kilho', 'kilho', 'charles','charles'],
                  'year' : [2014, 2015, 2016, 2015, 2016],
                  'points' : [1.5, 1.7, 3.6, 2.4, 2.9]}
data

{'names ': ['kilho', 'kilho', 'kilho', 'charles', 'charles'],
 'year': [2014, 2015, 2016, 2015, 2016],
 'points': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [24]:
df = pd.DataFrame(data, columns=['year','names','points','penalty'],
                index = ['one','two','threes','four','five'])


In [25]:
df

year names  points penalty
one     2014   NaN     1.5     NaN
two     2015   NaN     1.7     NaN
threes  2016   NaN     3.6     NaN
four    2015   NaN     2.4     NaN
five    2016   NaN     2.9     NaN

In [8]:
df.year

one       2014
two       2015
threes    2016
four      2015
five      2016
Name: year, dtype: int64

In [10]:
df[['year','points']]

year  points
one     2014     1.5
two     2015     1.7
threes  2016     3.6
four    2015     2.4
five    2016     2.9

In [11]:
df.penalty =0.5

In [12]:
df

year names  points  penalty
one     2014   NaN     1.5      0.5
two     2015   NaN     1.7      0.5
threes  2016   NaN     3.6      0.5
four    2015   NaN     2.4      0.5
five    2016   NaN     2.9      0.5

In [15]:
df['zeros'] = np.arange(5)

In [16]:
df

year names  points  penalty  zeros
one     2014   NaN     1.5      0.5      0
two     2015   NaN     1.7      0.5      1
threes  2016   NaN     3.6      0.5      2
four    2015   NaN     2.4      0.5      3
five    2016   NaN     2.9      0.5      4

In [17]:
val = pd.Series([-1.2, -1.5, -1.7], index=['one', 'threes','five'])

In [26]:
df['debt'] = val

In [27]:
df

year names  points penalty  debt
one     2014   NaN     1.5     NaN  -1.2
two     2015   NaN     1.7     NaN   NaN
threes  2016   NaN     3.6     NaN  -1.5
four    2015   NaN     2.4     NaN   NaN
five    2016   NaN     2.9     NaN  -1.7

In [29]:
df['net_points'] = df.points - df.penalty

In [30]:
df

year names  points penalty  debt net_points
one     2014   NaN     1.5     NaN  -1.2        NaN
two     2015   NaN     1.7     NaN   NaN        NaN
threes  2016   NaN     3.6     NaN  -1.5        NaN
four    2015   NaN     2.4     NaN   NaN        NaN
five    2016   NaN     2.9     NaN  -1.7        NaN

In [31]:
df['high_points'] = df['net_points'] > 2.0

In [38]:
df

year names  points penalty  debt net_points
one     2014   NaN     1.5     NaN  -1.2        NaN
two     2015   NaN     1.7     NaN   NaN        NaN
threes  2016   NaN     3.6     NaN  -1.5        NaN
four    2015   NaN     2.4     NaN   NaN        NaN
five    2016   NaN     2.9     NaN  -1.7        NaN

In [39]:
del df["year"]


In [40]:
df

names  points penalty  debt net_points
one      NaN     1.5     NaN  -1.2        NaN
two      NaN     1.7     NaN   NaN        NaN
threes   NaN     3.6     NaN  -1.5        NaN
four     NaN     2.4     NaN   NaN        NaN
five     NaN     2.9     NaN  -1.7        NaN

In [41]:
df.columns

Index(['names', 'points', 'penalty', 'debt', 'net_points'], dtype='object')

In [53]:
df.loc['threes':"five",'points':'penalty']

points penalty
threes     3.6     NaN
four       2.4     NaN
five       2.9     NaN

In [59]:
df['points']

one       1.5
two       1.7
threes    3.6
four      2.4
five      2.9
Name: points, dtype: float64

In [62]:
df.loc['seven'] = ['cho',4.0,1,1,1]

In [63]:
df

names  points penalty  debt net_points
one      NaN     1.5     NaN  -1.2        NaN
two      NaN     1.7     NaN   NaN        NaN
threes   NaN     3.6     NaN  -1.5        NaN
four     NaN     2.4     NaN   NaN        NaN
five     NaN     2.9     NaN  -1.7        NaN
seven    cho     4.0       1   1.0          1

In [64]:
df.iloc[3]

names         NaN
points        2.4
penalty       NaN
debt          NaN
net_points    NaN
Name: four, dtype: object

In [68]:
df.iloc[1,1]

1.7

In [69]:
df['points'] > 2.0

one       False
two       False
threes     True
four       True
five       True
seven      True
Name: points, dtype: bool

In [74]:
df.loc[df['points']>2.0, ]

names  points penalty  debt net_points
threes   NaN     3.6     NaN  -1.5        NaN
four     NaN     2.4     NaN   NaN        NaN
five     NaN     2.9     NaN  -1.7        NaN
seven    cho     4.0       1   1.0          1

In [75]:
df.loc[df['points']==4.0, ['names','points']]

names  points
seven   cho     4.0

In [77]:
df.loc[(df['points']>2) & (df['points'] <3)]

names  points penalty  debt net_points
four   NaN     2.4     NaN   NaN        NaN
five   NaN     2.9     NaN  -1.7        NaN